#
# Since: April, 2022
# Author: loic.lefevre
# Name: Dockerfile.ATPSFree19
# Description: Dockerfile to build Oracle Autonomous Transaction Processing Always Free 19c
#
# Copyright 2022 Loïc Lefèvre
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM alpine:3
#FROM oraclelinux:8-slim
#FROM debian:bullseye-slim
#FROM openjdk:17.0.2

ARG BUILD_MODE

ENV PATH="${PATH}":/opt/oracle

COPY container-entrypoint.sh dragonlite adbs.ini privateKey /opt/oracle
#COPY container-entrypoint.sh dragonlite-1.0.0-SNAPSHOT-jar-with-dependencies.jar adbs.ini privateKey ${ORACLE_BASE}

WORKDIR /opt/oracle

#HEALTHCHECK CMD /opt/oracle/healthcheck.sh >/dev/null || exit 1

ENTRYPOINT ["container-entrypoint.sh"]

#ENV GLIBC_REPO=https://github.com/sgerrand/alpine-pkg-glibc
#ENV GLIBC_VERSION=2.30-r0
#
#RUN set -ex && \
#    apk --update add libstdc++ curl ca-certificates && \
#    for pkg in glibc-${GLIBC_VERSION} glibc-bin-${GLIBC_VERSION}; \
#        do curl -sSL ${GLIBC_REPO}/releases/download/${GLIBC_VERSION}/${pkg}.apk -o /tmp/${pkg}.apk; done && \
#    apk add --allow-untrusted /tmp/*.apk && \
#    rm -v /tmp/*.apk && \
#    /usr/glibc-compat/sbin/ldconfig /lib /usr/glibc-compat/lib

